"""Train and evaluate a U-Net segmentation model on BraTS data.

Downstream experiment design (validates hypothesis H4):

  Condition A — "real": train on real pathological images + real masks (baseline).
  Condition B — "baseline_synthetic": train on synthetic images generated by
      baseline CycleGAN (G_BA(real_B)) paired with proxy masks from real
      pathological training slices.
  Condition C — "fb_synthetic": same as B but using FB-CycleGAN images.

All conditions are evaluated on held-out REAL BraTS test images + masks.
Higher Dice for FB-CycleGAN condition confirms that its outputs are more
structurally honest, producing better downstream segmentation models (H4).

Proxy mask assignment for synthetic images:
  Since G_BA(real_B) translates healthy images to synthetic pathological,
  there are no direct ground-truth masks. We assign proxy masks by randomly
  sampling a mask from the real pathological TRAINING split. This is a
  standard technique in domain-adaptation literature.

Usage:
    # Train on real images (baseline Dice)
    python scripts/train_downstream.py --mode real \
        --data-dir data/processed --output-dir outputs/downstream/real

    # Generate synthetic images first (requires trained generator checkpoint)
    python scripts/train_downstream.py --mode generate \
        --checkpoint outputs/checkpoints/baseline_cyclegan/final.pt \
        --data-dir data/processed \
        --output-dir outputs/downstream/baseline_synthetic/images

    # Train on synthetic images from baseline CycleGAN
    python scripts/train_downstream.py --mode synthetic \
        --synthetic-dir outputs/downstream/baseline_synthetic/images \
        --data-dir data/processed \
        --output-dir outputs/downstream/baseline_synthetic

    # Compare results
    python scripts/train_downstream.py --mode compare \
        --results-dir outputs/downstream
"""
from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.config import ExperimentConfig, ModelConfig
from src.downstream.unet import UNet
from src.downstream.seg_dataset import SegmentationDataset
from src.models import create_generator
from src.utils import set_seed, get_logger, ensure_dir


# ---------------------------------------------------------------------------
# Dice loss + metric
# ---------------------------------------------------------------------------

def dice_loss(pred: torch.Tensor, target: torch.Tensor, smooth: float = 1.0) -> torch.Tensor:
    """Soft Dice loss for binary segmentation.

    Args:
        pred: Predicted probabilities (B, 1, H, W) in [0, 1].
        target: Binary ground truth (B, 1, H, W) in {0, 1}.
        smooth: Laplace smoothing to avoid division by zero.

    Returns:
        Scalar Dice loss in [0, 1] (lower is better).
    """
    pred_flat = pred.view(pred.size(0), -1)
    tgt_flat = target.view(target.size(0), -1)
    intersection = (pred_flat * tgt_flat).sum(dim=1)
    dice = (2.0 * intersection + smooth) / (pred_flat.sum(dim=1) + tgt_flat.sum(dim=1) + smooth)
    return 1.0 - dice.mean()


def dice_score(pred: torch.Tensor, target: torch.Tensor, threshold: float = 0.5) -> float:
    """Hard Dice score (binarized prediction).

    Args:
        pred: Predicted probabilities (B, 1, H, W).
        target: Binary ground truth (B, 1, H, W).
        threshold: Binarization threshold.

    Returns:
        Mean Dice score in [0, 1] (higher is better).
    """
    pred_bin = (pred > threshold).float()
    pred_flat = pred_bin.view(pred_bin.size(0), -1)
    tgt_flat = target.view(target.size(0), -1)
    intersection = (pred_flat * tgt_flat).sum(dim=1)
    denom = pred_flat.sum(dim=1) + tgt_flat.sum(dim=1)
    # Avoid division by zero: empty prediction on empty target = 1
    score = torch.where(denom > 0, 2.0 * intersection / denom, torch.ones_like(intersection))
    return score.mean().item()


# ---------------------------------------------------------------------------
# Synthetic image generation
# ---------------------------------------------------------------------------

class HealthyDataset(Dataset):
    """Minimal dataset that loads healthy (domain B) test slices for generation."""

    def __init__(self, processed_dir: str, split: str = "train") -> None:
        super().__init__()
        processed_dir = Path(processed_dir)
        split_path = processed_dir / "split.json"
        with open(split_path) as f:
            split_data = json.load(f)
        patient_ids = set(split_data[split])

        self.paths = []
        healthy_dir = processed_dir / "healthy"
        if healthy_dir.exists():
            for p in sorted(healthy_dir.glob("*.npy")):
                stem = p.stem
                parts = stem.rsplit("_slice", 1)
                if len(parts) == 2 and parts[0] in patient_ids:
                    self.paths.append(p)

    def __len__(self) -> int:
        return len(self.paths)

    def __getitem__(self, idx: int) -> dict:
        arr = np.load(self.paths[idx]).astype(np.float32)
        arr = np.clip(arr, -3.0, 3.0) / 3.0
        tensor = torch.from_numpy(arr).unsqueeze(0)
        return {"image": tensor, "stem": self.paths[idx].stem}


def generate_synthetic_images(
    checkpoint_path: str,
    processed_dir: str,
    output_dir: str,
    split: str = "train",
    batch_size: int = 4,
    device: torch.device = torch.device("cpu"),
) -> None:
    """Generate synthetic pathological images (G_BA(healthy)) and save as .npy.

    Args:
        checkpoint_path: Path to CycleGAN checkpoint.
        processed_dir: Processed data directory.
        output_dir: Directory to save synthetic .npy images.
        split: Dataset split to generate from (uses healthy images).
        batch_size: Generation batch size.
        device: Torch device.
    """
    state = torch.load(checkpoint_path, map_location=device, weights_only=False)
    saved_cfg = state.get("config", {})
    model_cfg_dict = saved_cfg.get("model", {}) if isinstance(saved_cfg, dict) else {}

    model_cfg = ModelConfig(
        input_channels=model_cfg_dict.get("input_channels", 1),
        output_channels=model_cfg_dict.get("output_channels", 1),
        ngf=model_cfg_dict.get("ngf", 64),
    )

    G_BA = create_generator(model_cfg).to(device)
    G_BA.load_state_dict(state["G_BA"])
    G_BA.eval()

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    dataset = HealthyDataset(processed_dir, split=split)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False, num_workers=0)

    print(f"Generating {len(dataset)} synthetic pathological images...")

    with torch.no_grad():
        for batch in tqdm(loader, desc="Generating"):
            real_B = batch["image"].to(device)
            fake_A = G_BA(real_B)  # synthetic pathological

            for i, stem in enumerate(batch["stem"]):
                img = fake_A[i, 0].cpu().numpy()  # (H, W)
                np.save(output_dir / f"{stem}.npy", img.astype(np.float32))

    print(f"Saved {len(dataset)} synthetic images to {output_dir}")


# ---------------------------------------------------------------------------
# U-Net training
# ---------------------------------------------------------------------------

def train_unet(
    train_dataset: SegmentationDataset,
    val_dataset: SegmentationDataset,
    output_dir: Path,
    epochs: int = 50,
    batch_size: int = 4,
    lr: float = 1e-4,
    device: torch.device = torch.device("cpu"),
    seed: int = 42,
) -> dict[str, list[float]]:
    """Train U-Net with combined Dice + BCE loss.

    Args:
        train_dataset: Training segmentation dataset.
        val_dataset: Validation segmentation dataset.
        output_dir: Directory to save checkpoints and logs.
        epochs: Number of training epochs.
        batch_size: Batch size.
        lr: Learning rate.
        device: Torch device.
        seed: Random seed.

    Returns:
        Dict with "train_dice", "val_dice", "train_loss", "val_loss" lists.
    """
    set_seed(seed)
    logger = get_logger("unet_trainer", log_dir=str(output_dir / "logs"))

    model = UNet(in_channels=1, base_features=32).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True,
        num_workers=2, drop_last=True, pin_memory=True,
    )
    val_loader = DataLoader(
        val_dataset, batch_size=batch_size, shuffle=False, num_workers=2,
    )

    history: dict[str, list[float]] = {
        "train_dice": [], "val_dice": [], "train_loss": [], "val_loss": [],
    }

    best_val_dice = 0.0

    for epoch in range(1, epochs + 1):
        # --- Train ---
        model.train()
        train_loss_sum = 0.0
        train_dice_sum = 0.0
        n_train = 0

        for batch in tqdm(train_loader, desc=f"Epoch {epoch}/{epochs} [train]", leave=False):
            images = batch["image"].to(device)
            masks = batch["mask"].to(device)

            optimizer.zero_grad()
            preds = model(images)
            loss = dice_loss(preds, masks) + F.binary_cross_entropy(preds, masks)
            loss.backward()
            optimizer.step()

            train_loss_sum += loss.item() * images.size(0)
            train_dice_sum += dice_score(preds.detach(), masks) * images.size(0)
            n_train += images.size(0)

        scheduler.step()

        # --- Validate ---
        model.eval()
        val_loss_sum = 0.0
        val_dice_sum = 0.0
        n_val = 0

        with torch.no_grad():
            for batch in tqdm(val_loader, desc=f"Epoch {epoch}/{epochs} [val]", leave=False):
                images = batch["image"].to(device)
                masks = batch["mask"].to(device)
                preds = model(images)
                loss = dice_loss(preds, masks) + F.binary_cross_entropy(preds, masks)
                val_loss_sum += loss.item() * images.size(0)
                val_dice_sum += dice_score(preds, masks) * images.size(0)
                n_val += images.size(0)

        train_loss = train_loss_sum / max(n_train, 1)
        val_loss = val_loss_sum / max(n_val, 1)
        train_d = train_dice_sum / max(n_train, 1)
        val_d = val_dice_sum / max(n_val, 1)

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_dice"].append(train_d)
        history["val_dice"].append(val_d)

        logger.info(
            "Epoch %d/%d  train_loss=%.4f  val_loss=%.4f  train_dice=%.4f  val_dice=%.4f",
            epoch, epochs, train_loss, val_loss, train_d, val_d,
        )

        # Save best model
        if val_d > best_val_dice:
            best_val_dice = val_d
            torch.save(model.state_dict(), output_dir / "best_unet.pt")

    torch.save(model.state_dict(), output_dir / "final_unet.pt")
    with open(output_dir / "history.json", "w") as f:
        json.dump(history, f, indent=2)

    logger.info("Training complete. Best val Dice: %.4f", best_val_dice)
    return history


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

def evaluate_unet(
    checkpoint_path: str,
    test_dataset: SegmentationDataset,
    device: torch.device,
    batch_size: int = 4,
) -> float:
    """Evaluate U-Net Dice score on a test dataset.

    Args:
        checkpoint_path: Path to U-Net state_dict .pt file.
        test_dataset: Test segmentation dataset (real images + real masks).
        device: Torch device.
        batch_size: Batch size.

    Returns:
        Mean Dice score over the test set.
    """
    model = UNet(in_channels=1, base_features=32).to(device)
    model.load_state_dict(torch.load(checkpoint_path, map_location=device, weights_only=True))
    model.eval()

    loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

    dice_sum = 0.0
    n = 0
    with torch.no_grad():
        for batch in loader:
            images = batch["image"].to(device)
            masks = batch["mask"].to(device)
            preds = model(images)
            dice_sum += dice_score(preds, masks) * images.size(0)
            n += images.size(0)

    return dice_sum / max(n, 1)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Downstream U-Net segmentation evaluation.")
    parser.add_argument(
        "--mode",
        type=str,
        required=True,
        choices=["real", "generate", "synthetic", "compare"],
        help=(
            "real: train on real images; "
            "generate: generate synthetic images from a checkpoint; "
            "synthetic: train on synthetic images; "
            "compare: load and print all result JSONs."
        ),
    )
    parser.add_argument("--data-dir", type=str, default="data/processed")
    parser.add_argument("--output-dir", type=str, default="outputs/downstream")
    parser.add_argument(
        "--checkpoint",
        type=str,
        default=None,
        help="CycleGAN checkpoint (required for --mode generate).",
    )
    parser.add_argument(
        "--synthetic-dir",
        type=str,
        default=None,
        help="Directory of synthetic .npy images (required for --mode synthetic).",
    )
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--device",
        type=str,
        default="cuda" if torch.cuda.is_available() else "cpu",
    )
    parser.add_argument("--split", type=str, default="train", help="Split to generate from.")
    args = parser.parse_args()

    device = torch.device(args.device)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    if args.mode == "generate":
        if args.checkpoint is None:
            parser.error("--checkpoint is required for --mode generate")
        generate_synthetic_images(
            checkpoint_path=args.checkpoint,
            processed_dir=args.data_dir,
            output_dir=str(output_dir / "images"),
            split=args.split,
            batch_size=args.batch_size,
            device=device,
        )
        return

    # ------------------------------------------------------------------
    if args.mode == "compare":
        results_dir = Path(args.output_dir)
        all_results = {}
        for result_file in sorted(results_dir.rglob("test_dice.json")):
            with open(result_file) as f:
                data = json.load(f)
            label = result_file.parent.name
            all_results[label] = data.get("test_dice", "N/A")

        if not all_results:
            print("No test_dice.json files found in", results_dir)
        else:
            print("\n=== Downstream Segmentation Results ===")
            for label, dice in sorted(all_results.items()):
                print(f"  {label:40s}: Dice = {dice:.4f}")
        return

    # ------------------------------------------------------------------
    # Build datasets
    synthetic_dir = args.synthetic_dir if args.mode == "synthetic" else None

    train_dataset = SegmentationDataset(
        processed_dir=args.data_dir,
        split="train",
        synthetic_image_dir=synthetic_dir,
        augment=True,
    )
    val_dataset = SegmentationDataset(
        processed_dir=args.data_dir,
        split="val",
        # Always validate on real images
        synthetic_image_dir=None,
        augment=False,
    )
    test_dataset = SegmentationDataset(
        processed_dir=args.data_dir,
        split="test",
        synthetic_image_dir=None,
        augment=False,
    )

    # Train
    print(f"\nTraining U-Net (mode={args.mode}, epochs={args.epochs})...")
    history = train_unet(
        train_dataset=train_dataset,
        val_dataset=val_dataset,
        output_dir=output_dir,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        device=device,
        seed=args.seed,
    )

    # Evaluate best checkpoint on test set
    best_ckpt = output_dir / "best_unet.pt"
    if best_ckpt.exists():
        test_dice = evaluate_unet(str(best_ckpt), test_dataset, device, args.batch_size)
    else:
        test_dice = evaluate_unet(str(output_dir / "final_unet.pt"), test_dataset, device, args.batch_size)

    print(f"\n=== Test Set Dice: {test_dice:.4f} ===")

    # Save result
    result = {
        "mode": args.mode,
        "test_dice": test_dice,
        "best_val_dice": max(history["val_dice"]) if history["val_dice"] else 0.0,
        "epochs": args.epochs,
        "synthetic_dir": str(synthetic_dir) if synthetic_dir else None,
    }
    with open(output_dir / "test_dice.json", "w") as f:
        json.dump(result, f, indent=2)
    print(f"Results saved to {output_dir / 'test_dice.json'}")


if __name__ == "__main__":
    main()
